export const habitIcons = {
        Emoções: [
            "emoticon-happy-outline",
            "emoticon-sad-outline",
            "emoticon-angry-outline",
            "emoticon-cool-outline",
            "emoticon-cry-outline",
            "emoticon-excited-outline",
            "emoticon-tongue-outline",
            "heart-outline",
            "heart-broken-outline",
            "brain",
        ],
        Rotina: [
            "weather-sunny",
            "weather-night",
            "alarm",
            "book-open-page-variant",
            "briefcase-outline",
            "bed",
            "coffee-outline",
            "shower",
            "cellphone",
            "laptop",
            "calendar-month-outline",
            "target",
        ],
        Saúde: [
            "pill",
            "run",
            "bike",
            "dumbbell",
            "yoga",
            "water",
            "apple",
            "tooth-outline",
            "heart-pulse",
            "sleep",
        ],
        Saúde: [
            "pill",
            "run",
            "bike",
            "dumbbell",
            "yoga",
            "water",
            "apple",
            "tooth-outline",
            "heart-pulse",
            "sleep",
        ],
        // Vícios: [
        //     "cigarette",
        //     "glass-wine",
        //     "beer-outline",
        //     "food-burger",
        //     "food-apple-outline",
        //     "controller-classic-outline",
        //     "cellphone-sound",
        //     "television",
        //     "shopping",
        //     "cash",
        //     "credit-card-outline",
        //     "slot-machine-outline",
        //     "fire",
        // ],
        // BemEstar: [
        //     "spa-outline",
        //     "music-note",
        //     "camera-outline",
        //     "airplane",
        //     "palette-outline",
        //     "earbuds",
        //     "forest",
        //     "white-balance-sunny",
        //     "weather-night",
        //     "meditation",
        //     "flower",
        //     "beach",
        // ],
    };